name: Bergie
favicon: null
layout_spectrum: 0.8032312630675733
typography_spectrum: 0.09763237088918686
title: Henri Bergius
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75936-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
