name: Bergie
favicon: null
layout_spectrum: 0.1708
typography_spectrum: 0.65438
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75936-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0B8'
    - '#000000'
    - '#888880'
    - '#000000'
    - '#000000'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
author:
  name: Henri Bergius
  email: "henri.bergius@iki.fi"
  url: "http://bergie.iki.fi"
