name: Bergie
favicon: null
layout_spectrum: 0.1708
typography_spectrum: 0.65438
author:
  name: Henri Bergius
  email: henri.bergius@iki.fi
  url: 'http://bergie.iki.fi'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75936-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030504'
    - '#ededed'
    - '#748399'
    - '#48555e'
    - '#e4e44c'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose:
  - name: follow
    item: null
    url: null
