analytics:
  google: UA-75936-2
color:
  brandColors:
    - '#C0C0B8'
    - '#000000'
    - '#888880'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.8032312630675733
name: Bergie
opengraph: {}
purpose:
  - name: follow
typography_spectrum: 0.09763237088918686
